//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageNotification.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChienDichTruyenThong
    {
        public decimal AutoID { get; set; }
        public string TEN_CHIEN_DICH { get; set; }
        public Nullable<int> HINH_THUC_TRUYEN_THONG { get; set; }
        public Nullable<int> KHU_VUC_ID { get; set; }
        public Nullable<int> PHAM_VI { get; set; }
        public Nullable<System.DateTime> NGAY_THUC_HIEN { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<int> DOI_TUONG { get; set; }
        public Nullable<int> TRANG_THAI { get; set; }
        public Nullable<int> SO_LUONG_THANH_CONG { get; set; }
        public Nullable<int> TINH_ID { get; set; }
        public Nullable<int> HUYEN_ID { get; set; }
        public Nullable<int> XA_ID { get; set; }
    }
}
