//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageNotification.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tinh
    {
        public decimal AutoID { get; set; }
        public int TINH_ID { get; set; }
        public string TENTINH { get; set; }
        public int VUNGMIEN_ID { get; set; }
    }
}
