//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageNotification.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xa
    {
        public decimal AutoID { get; set; }
        public Nullable<double> XA_ID { get; set; }
        public string TENXA { get; set; }
        public Nullable<double> HUYEN_ID { get; set; }
    }
}
